### PR TITLE
fix: add stopPropertySequence before loadPropertySequence in setup_sequenced_event

### LINKED ISSUE #352: A running DIO sequence prevents repeated mda_run() (related to issue #306, #307)
With hardware sequencing enabled and a DIO port involved in the sequence (used for fluorescent channel specification, useful for situations involving AOTF, for example), the 2nd `mda_run` of the same sequence generates the following error due to a running sequence on the DIO port (similar to #306 except that was for AO port):

```
Exception in thread Thread-16 (run):
Traceback (most recent call last):
  File "C:\Users\scape20\miniconda3\envs\pycroman\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\scape20\miniconda3\envs\pycroman\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\scape20\miniconda3\envs\pycroman\Lib\site-packages\pymmcore_plus\mda\_runner.py", line 211, in run
    raise error
  File "C:\Users\scape20\miniconda3\envs\pycroman\Lib\site-packages\pymmcore_plus\mda\_runner.py", line 205, in run
    self._run(engine, events)
  File "C:\Users\scape20\miniconda3\envs\pycroman\Lib\site-packages\pymmcore_plus\mda\_runner.py", line 279, in _run
    engine.setup_event(event)
  File "C:\Users\scape20\miniconda3\envs\pycroman\Lib\site-packages\pymmcore_plus\mda\_engine.py", line 166, in setup_event
    self.setup_sequenced_event(event)
  File "C:\Users\scape20\miniconda3\envs\pycroman\Lib\site-packages\pymmcore_plus\mda\_engine.py", line 358, in setup_sequenced_event
    core.loadPropertySequence(dev, prop, value_sequence)
RuntimeError: Error in device "NIDAQDO-Dev1/port0": A sequence is running on this port.  Please stop this sequence first. (2001)
```

Could we add something to similar to `core.stopStageSequence(zstage)` for the DIO port? Thanks!

lin

### PR DESCRIPTION
**Pull request by tlambert03**
(hopefully) fixes #352 

@linshaova i've made a couple additional changes here that (technically) undo some of changes I made in #307, but I think it's a better overall fix.  basically, I've moved all of the `core.stop<Thing>Sequence` calls into the `teardown_event` event method of the engine (which always gets called at the end of an event) and removed the "safety" calls to `stop<Thing>Sequence` from the setup_event method.  I've also added a couple more `stop<Thing>Sequence` calls for XYStageDevice and ExposureSequence.

If you have a moment, it would be great if you confirm whether this branch fixes your issues

### CODE REVIEW

**Comment by linshaova** [comment]
worked!

**Comment by tlambert03** [comment]
Thanks!

**Comment by linshaova** [comment]
Sorry I spoke too soon; I wasn't testing the MDAsequence with a property sequence and I haven't been able to update `pymmcore_plus` installation via either `pip` or `conda` (`teardown_event` in the installed version still has only 2 lines; version 0.9.5 is what's installed via `pip`.)

**Comment by tlambert03** [comment]
Ok, yeah I didn't release this to pypi yet, so you'd need to actually checkout this branch locally to have tested it.  I can hold off on releasing.  Did you notice that it doesn't actually work?  Or just that you probably didn't test it properly?

**Comment by linshaova** [comment]
Okay I checked out the latest update via `git`. New issue: the previously fixed issue regarding `stopStageSequence` has reappeared, indicating it's actually not called as intended in `teardown_event`. I traced into there, and can confirm that all lines in the `if isinstance(event, SequencedEvent):` block are bypassed. And `logger.info(event)` produces: ` 2024-06-10 15:52:42,145 - pymmcore-plus - INFO - (_engine.py:332) index=mappingproxy({'z': 40}) z_pos=200.0`

**Comment by tlambert03** [comment]
ok, thanks for confirming, I'll add back the old fix for now (and re-release) and we can try to fix teardown later

**Comment by tlambert03** [comment]
v0.10.1 building now with the fix.  try in about 15 min

**Pull request merged**
