### PR TITLE
fix: fix excess reading of frame metadata in OMEZarrWriter

### PR DESCRIPTION
**Pull request by wl-stepp**
I had the problem that reading appending and re-writing the frame meta data become pretty slow for long acquisitions. First simple approach here to gather the metadata during the acqusition and write it on sequenceFinished.
Tests passing locally, not sure if frame metadata is tested though. Can have a look next week.

### CODE REVIEW

**Comment by tlambert03** [comment]
yeah, this looks sound to me.  Have you been using it and liking it?

**Comment by wl-stepp** [comment]
Yes, made the stack viewer work for long acquisitions reliably.

**Comment by tlambert03** [comment]
Ready for merge then?

**Comment by tlambert03** [comment]
will merge in a moment.  In the future, if you're done tinkering with a PR, feel free take it out of "draft" and click request review.

**Pull request merged**
